### ISSUE TITLE
А где проект-то емае? Я не на той ветке что ли смотрю или вы создали в каждой папке readme и думаете что они скомпилятся в готовый проект?

### ISSUE THREAD

**Issue by dodokek** [vitosotdihaet/baking-bread#23]
Мда

**Comment by vitosotdihaet** [comment]
# Сынок ты ебаный
Помой ноги и ложись спать если не можешь даже открыть другую ветку, чтобы увидеть часть проекта, которая уже работает.
Ридмишники нужны для разработчиков и простых зевак с гитхаба, если ты такой умный _**сука**_ может сам запустишь свою онлайн-пекарню, гандон
# Чем ты лучше
Я посмотрел твои репозитории и что-то не вижу стоящих проектов, думаешь поступил в **МФТИ** и теперь тебе все можно?
Ты, блядь необразованная, бездарная сука пишущая проги на ассемблере **негр** чисто, надеюсь на втором курсе тебе наконец дадут заняться нормальным делом - _сборкой процессоров Байкал_.
Тем более у вас щас китайский введут надеюсь вас в шанхай заберут и выебут в жопу за то, что у вас низкий соц. кредит

**Comment by vitosotdihaet** [comment]
# Хорошо мы все исправим 😁

**Comment by dodokek** [comment]
Здравствуйте **Виталий**, спасибо за ваш ответ! Я был польщен тем, что вы тоже уважаете процессоры Эльбрус (Не Байкал, все ошибаются это бывает, я понимаю). Я посмотрел _другую_ ветку вашего проекта и нашел там еще больше папок с readme. В связи с этим я бы хотел удостоверится, что вы знаете, как писать онлайн-пекарни. На всякий случай повторюсь, что проект нужно писать на языках программирования типа python(хотя конечно я больше уважаю _Ass емблер_), а **не на языке разметки.**

**Comment by vitosotdihaet** [comment]
# александр у вас что мать мертва 😁

**Comment by dodokek** [comment]
Нет, она просто на другой ветке
